services:
  drupal:
    image: drupal:11-apache
    container_name: "${BRANCH_NAME:-source}_drupal"
    env_file:
      - .env
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    networks:
      - branch_network
      - traefik_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: "${BRANCH_NAME:-source}_db"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - branch_network
    restart: unless-stopped

volumes:
  db_data:
    name: "${BRANCH_NAME:-source}_db_data"

networks:
  branch_network:
    name: "${BRANCH_NAME:-source}_network"
    driver: bridge
  traefik_network:
    name: traefik_network
    external: true
